import { useState } from "react";
import { jsPDF } from "jspdf";
import PDF from "../PDF";

export default function ExportPDF({ profile }) {
  const [error, setError] = useState("");

  const generatePDF = () => {
    if (!profile || typeof profile !== "object") return;

    // collect filled fields
    const filledFields = Object.entries(profile)
      .filter(([_, value]) => value && String(value).trim())
      .map(([label, value]) => ({
        label,
        value: String(value).trim(),
      }));

    // no data
    if (filledFields.length === 0) {
      setError("No data to export. Please fill in some fields first.");
      setTimeout(() => setError(""), 1600);
      return;
    }

    setError("");

    const doc = new jsPDF();

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    const margin = 20;
    const maxWidth = pageWidth - margin * 2;

    let yPosition = margin;

    const checkAddPage = (requiredSpace) => {
      if (yPosition + requiredSpace > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
    };

    // metadata
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);

    const date = new Date();

    const formattedDate = date.toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const formattedTime = date.toLocaleTimeString("en-US");

    doc.text(
      `Exported on: ${formattedDate} at ${formattedTime}`,
      margin,
      yPosition,
    );

    yPosition += 5;

    doc.text(`Total fields: ${filledFields.length}`, margin, yPosition);

    yPosition += 10;

    doc.setDrawColor(0, 0, 0);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);

    yPosition += 10;

    // fields
    filledFields.forEach((field) => {
      checkAddPage(30);

      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(100, 100, 100);

      doc.text(field.label.toUpperCase(), margin, yPosition);

      yPosition += 6;

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(0, 0, 0);

      const lines = doc.splitTextToSize(field.value, maxWidth);

      lines.forEach((line) => {
        checkAddPage(6);
        doc.text(line, margin, yPosition);
        yPosition += 6;
      });

      yPosition += 8;
    });

    // footer
    checkAddPage(20);

    yPosition = pageHeight - margin;

    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(150, 150, 150);

    doc.text("Generated by Fillio", pageWidth / 2, yPosition, {
      align: "center",
    });

    doc.save(`fillio-profile-${date.toISOString().split("T")[0]}.pdf`);
  };

  return (
    <>
      <button
        onClick={generatePDF}
        className="w-full py-2.5 px-3 rounded-lg border border-[#e2e8f0] text-[12px] font-medium cursor-pointer transition-all duration-200 bg-white text-[#0f172a] hover:bg-[#f0f0f0] hover:border-[#0f172a] flex items-center justify-start gap-2.5"
      >
        <PDF />
        Export as PDF
      </button>

      {error && (
        <div className="text-[11px] text-[#dc2626] mt-1 text-center">
          {error}
        </div>
      )}
    </>
  );
}
