export const FIELDS = [
  { key: "email", label: "email" },
  { key: "prn", label: "prn" },
  { key: "fullName", label: "full name" },
  { key: "dob", label: "dob (yyyy-mm-dd)" },
  { key: "mobile", label: "mobile" },
  { key: "gender", label: "gender (male/female)" },
  { key: "college", label: "college name" },
  { key: "course", label: "course" },
  { key: "branch", label: "branch" },
  { key: "passYear", label: "year of passing" },
  { key: "tenthPercent", label: "10th %" },
  { key: "twelfthPercent", label: "12th %" },
  { key: "diplomaPercent", label: "diploma %" },
  { key: "degreePercent", label: "be/btech %" },
  { key: "cocubesScore", label: "cocubes score" },
  { key: "hackerrankRating", label: "hackerrank rating (0-5)" },
  { key: "hackerrankLink", label: "hackerrank profile link" },
  { key: "leetcodeScore", label: "leetcode score" },
  { key: "leetcodeLink", label: "leetcode profile link" },
  { key: "codechefRating", label: "codechef rating (0-5)" },
  { key: "codechefLink", label: "codechef profile link" },
  { key: "hackerearthRating", label: "hackerearth rating (0-5)" },
  { key: "hackerearthLink", label: "hackerearth profile link" },
  { key: "projects", label: "projects", textarea: true },
  {
    key: "techAchievements",
    label: "technical achievements",
    textarea: true,
  },
  {
    key: "personalAchievements",
    label: "personal achievements",
    textarea: true,
  },
];
